// TODO： 联系我们（使用条款，内容差不多）

import React from 'react'

function ContactUs(props) {
  return (
    <div className='container'>
      <h4>Contact Us</h4>

      <p style={{ marginTop: 60 }}>
        PLEASE READ THESE WEB SITE TERMS OF USE CAREFULLY BEFORE USING THIS WEB SITE (THE "WEB
        SITE"). THESE WEB SITE TERMS OF USE (THE "TERMS OF USE") GOVERN YOUR ACCESS TO AND USE OF
        THE WEB SITE. THE WEB SITE IS AVAILABLE FOR YOUR USE ONLY ON THE CONDITION THAT YOU AGREE TO
        THE TERMS OF USE SET FORTH BELOW. IF YOU DO NOT AGREE TO ALL OF THE TERMS OF USE, DO NOT
        ACCESS OR USE THE WEB SITE. BY ACCESSING OR USING THE WEB SITE, YOU AND THE ENTITY YOU ARE
        AUTHORISED TO REPRESENT (HEREINAFTER "YOU" OR "YOUR") SIGNIFY YOUR AGREEMENT TO BE BOUND BY
        THE TERMS OF USE.
      </p>
    </div>
  )
}

export default ContactUs
